name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-dev build-essential \
            libffi-dev libssl-dev libltdl-dev libsqlite3-dev libjpeg-dev libfreetype6-dev \
            libgles2-mesa-dev libglu1-mesa-dev

      - name: Install Android SDK & NDK
        run: |
          sudo mkdir -p /opt/android-sdk
          cd /opt/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d cmdline-tools
          export ANDROID_HOME=/opt/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses
          yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;23.1.7779620"

      - name: Install Buildozer & Cython
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install buildozer cython

      - name: Build APK
        env:
          ANDROIDSDK: /opt/android-sdk
          ANDROIDNDK: /opt/android-sdk/ndk/23.1.7779620
          PATH: /opt/android-sdk/platform-tools:/opt/android-sdk/build-tools/31.0.0:/opt/android-sdk/cmdline-tools/bin:$PATH
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: raffle-app
          path: bin/*.apk
